apiVersion: v1
kind: PersistentVolume
metadata:
  name: eu4wiki-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/eu4wiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eu4wiki-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: wikis
  name: eu4wiki-sv
  labels:
    app: eu4wiki-app
    service: eu4wiki-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: eu4wiki-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wikis
  name: eu4wiki-deployment
  labels:
    app: eu4wiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eu4wiki-app
      version: v1
  template:
    metadata:
      namespace: wikis
      labels:
        app: eu4wiki-app
        version: v1
    spec:
      containers:
      - name: eu4wiki-pukiwiki
        image: gnagaoka/eu4_legacy_wiki:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: eu4wiki-env-secret
        volumeMounts:
        - name: eu4wiki-persistent-storage
          mountPath: /var/www/html/wikidata
      volumes:
      - name: eu4wiki-persistent-storage
        persistentVolumeClaim:
          claimName: eu4wiki-pv-claim
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: wikis
  name: eu4-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "eu4wiki.popush.cloud"
    - "eu4.paradwiki.org"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wikis
  name: eu4wiki-vs
spec:
  hosts:
  - "eu4wiki.popush.cloud"
  gateways:
  - eu4-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: eu4wiki-sv
        port:
          number: 80
