apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ess"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
  selector:
    app: elasticsearch
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: elasticsearch:7.6.2
        name: elasticsearch
        envFrom:
        - secretRef:
            name: elasticsearch-env-secret
        ports:
        - containerPort: 9200
          name: elasticsearch
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: colle-del-gran-san-bernardo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "local.popush.cloud"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: elasticsearch-vs
spec:
  hosts:
  - "local.popush.cloud"
  gateways:
  - colle-del-gran-san-bernardo
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: elasticsearch
        port:
          number: 9200
