apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
    service: test
spec:
  ports:
  - port: 8080
    nodePort: 32000
    name: http
  selector:
    app: test
  type: NodePort