apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test 
        env:
        - name: HTTP_PORT
          value: 80
        image: mendhak/http-https-echo:17
        ports:
        - containerPort: 80