apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: backup
  name: ck2wiki-backup-batch
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ck2wiki-backup-docker
            image: istepanov/backup-to-s3
            envFrom:
              - secretRef:
                  name: ck2wiki-backup-env-secret
            volumeMounts:
              - name: ck2wiki-persistent-storage
                mountPath: /data
                readOnly: true
            args:
              - no-cron
          restartPolicy: OnFailure
          volumes:
            - name: ck2wiki-persistent-storage
              persistentVolumeClaim:
                claimName: ck2wiki-pv-claim
