apiVersion: v1
kind: PersistentVolume
metadata:
  name: ck3wiki-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ck3wiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ck3wiki-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
apiVersion: v1
---
kind: Service
metadata:
  namespace: wikis
  name: ck3wiki-sv
  labels:
    app: ck3wiki-app
    service: ck3wiki-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: ck3wiki-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wikis
  name: ck3wiki-deployment
  labels:
    app: ck3wiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ck3wiki-app
      version: v1
  template:
    metadata:
      namespace: wikis
      labels:
        app: ck3wiki-app
        version: v1
    spec:
      containers:
      - name: ck3wiki-mediawiki
        image: gnagaoka/ck3wiki:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: ck3wiki-env-secret
        volumeMounts:
        - name: ck3wiki-persistent-storage
          mountPath: /var/www/html/images
      volumes:
      - name: ck3wiki-persistent-storage
        persistentVolumeClaim:
          claimName: ck3wiki-pv-claim
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: wikis
  name: passo-dello-stelvio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "ck3wiki.popush.cloud"
    tls:
      mode: SIMPLE
      credentialName: ck3wiki-popush-cloud-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wikis
  name: ck3wiki-vs
spec:
  hosts:
  - "ck3wiki.popush.cloud"
  gateways:
  - passo-dello-stelvio
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ck3wiki-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: ck3wiki-letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: ck3wiki-letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ck3wiki-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: ck3wiki-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'ck3wiki.popush.cloud'
  issuerRef:
    name: ck3wiki-letsencrypt-issuer
    kind: ClusterIssuer
