apiVersion: v1
kind: Service
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-sv
  labels:
    app: rico-app
    service: rico-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: rico-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-deployment
  labels:
    app: rico-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rico-app
  template:
    metadata:
      namespace: ente-pubblico-per-il-benessere-sociale
      labels:
        app: rico-app
    spec:
      containers:
      - name: rico-springboot
        image: ghcr.io/matanki-saito/rico-app:0.0.11-app
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: reco-env-secret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: colle-delle-traversette
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "local.popush.cloud"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "local.popush.cloud"
    tls:
      mode: SIMPLE
      credentialName: httpbin-credential
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-vs
spec:
  hosts:
  - "local.popush.cloud"
  gateways:
  - colle-delle-traversette
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: rico-sv
        port:
          number: 80
