# external alertmanager yaml
global:
  resolve_timeout: 10m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5h
  receiver: 'discord'
receivers:
- name: 'null'
- name: discord
  discord_configs:
  - webhook_url: 'env.alertmanager.webhook'
    message: 'alert!'
