apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wikis
  name: wikidb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wikidb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wikis
  name: wikidb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: wikis
  name: wikidb
spec:
  ports:
  - port: 3306
  selector:
    app: wikidb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wikis
  name: wikidb
spec:
  selector:
    matchLabels:
      app: wikidb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wikidb
    spec:
      containers:
      - image: mysql:8.0.15
        name: wikidb
        envFrom:
        - secretRef:
            name: wikidb-env-secret
        ports:
        - containerPort: 3306
          name: wikidb
        volumeMounts:
        - name: wikidb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: wikidb-persistent-storage
        persistentVolumeClaim:
          claimName: wikidb-pv-claim
