apiVersion: v1
kind: Service
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: henrietta-sv
  labels:
    app: henrietta-app
    service: henrietta-sv
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: henrietta-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: p90
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "henrietta.popush.cloud"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "henrietta.popush.cloud"
    tls:
      mode: SIMPLE
      credentialName: henrietta-popush-cloud-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: henrietta-vs
spec:
  hosts:
  - "henrietta.popush.cloud"
  gateways:
  - p90
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: henrietta-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: henrietta-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: henrietta-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'henrietta.popush.cloud'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
