apiVersion: v1
kind: Service
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: henrietta-sv
  labels:
    app: henrietta-app
    service: henrietta-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: henrietta-app
