apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gangway
  name: gate-deployment
  labels:
    app: gate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-app
      version: v1
  template:
    metadata:
      namespace: gangway
      labels:
        app: gate-app
        version: v1
    spec:
      imagePullSecrets:
        - name: github-repository-secret
      containers:
        - name: gate-springboot
          image: ghcr.io/matanki-saito/gate-app:0.1.10
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 9000
          envFrom:
            - secretRef:
                name: gate-env-secret
