apiVersion: v1
kind: Service
metadata:
  namespace: gangway
  name: keycloak-sv
  labels:
    app: keycloak-app
    service: keycloak-sv
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: keycloak-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gangway
  name: keycloak-deployment
  labels:
    app: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
      version: v1
  template:
    metadata:
      namespace: gangway
      labels:
        app: keycloak-app
        version: v1
    spec:
      containers:
        - name: keycloak-docker
          image: quay.io/keycloak/keycloak
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: keycloak-env-secret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: gangway
  name: arai
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "keycloak.popush.cloud"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: gangway
  name: keycloak-vs
spec:
  hosts:
  - "keycloak.popush.cloud"
  gateways:
  - arai
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keycloak-letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: keycloak-letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: keycloak-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'keycloak.popush.cloud'
  issuerRef:
    name: keycloak-letsencrypt-issuer
    kind: ClusterIssuer
