apiVersion: v1
kind: Service
metadata:
  namespace: gangway
  name: gate-sv
  labels:
    app: gate-app
    service: gate-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9000
    targetPort: 9000
    name: grpc
  selector:
    app: gate-app
