apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-sv
  labels:
    app: wordpress-app
    service: wordpress-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: wordpress-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: wordpress
  name: wordpress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "paradoxian.popush.cloud"
    tls:
      mode: SIMPLE
      credentialName: paradoxian-popush-cloud-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wordpress
  name: wordpress-vs
spec:
  hosts:
  - "paradoxian.popush.cloud"
  gateways:
  - wordpress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: wordpress-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wordpress-letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: wordpress-letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: wordpress-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'paradoxian.popush.cloud'
  issuerRef:
    name: wordpress-letsencrypt-issuer
    kind: ClusterIssuer
