apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-sv
  labels:
    app: wordpress-app
    service: wordpress-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: wordpress-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: wordpress
  name: wordpress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "paradoxian.popush.cloud"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wordpress
  name: wordpress-vs
spec:
  hosts:
  - "paradoxian.popush.cloud"
  gateways:
  - wordpress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: wordpress-sv
        port:
          number: 80
