apiVersion: v1
kind: Service
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: triela-sv
  labels:
    app: triela-app
    service: triela-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: triela-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: triela-deployment
  labels:
    app: triela-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triela-app
      version: v1
  template:
    metadata:
      namespace: ente-pubblico-per-il-benessere-sociale
      labels:
        app: triela-app
        version: v1
    spec:
      containers:
      - name: triela-springboot
        image: gnagaoka/triela-app:0.3.13
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: triela-env-secret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: colle-clapier
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: triela-popush-cloud-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: triela-vs
spec:
  hosts:
  - "*"
  gateways:
  - colle-clapier
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: triela-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: triela-letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: triela-letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: triela-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: triela-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'triela.popush.cloud'
  issuerRef:
    name: triela-letsencrypt-issuer
    kind: ClusterIssuer
