apiVersion: v1
kind: Service
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-sv
  labels:
    app: rico-app
    service: rico-sv
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: rico-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-deployment
  labels:
    app: rico-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rico-app
      version: v1
  template:
    metadata:
      namespace: ente-pubblico-per-il-benessere-sociale
      labels:
        app: rico-app
        version: v1
    spec:
      imagePullSecrets:
      - name: github-repository-secret
      containers:
      - name: rico-springboot
        image: ghcr.io/matanki-saito/rico-app:0.0.11-app
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: reco-env-secret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: colle-delle-traversette
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "rico.popush.cloud"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "rico.popush.cloud"
    tls:
      mode: SIMPLE
      credentialName: rico-popush-cloud-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ente-pubblico-per-il-benessere-sociale
  name: rico-vs
spec:
  hosts:
  - "rico.popush.cloud"
  gateways:
  - colle-delle-traversette
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: rico-sv
        port:
          number: 80
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matanki.saito@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-private-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          accessKeyID: AKIAXMVOGSBVQQMRQ3TJ
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rico-popush-cloud-cert
  namespace: istio-system
spec:
  secretName: rico-popush-cloud-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - 'rico.popush.cloud'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
