name: Compile jsonnet

on:
  workflow_dispatch:
    inputs:
      info:
        description: 'manual trigger'

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: quay.io/coreos/jsonnet-ci
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          cd monitoring
          jb init
          jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.8
          ls
          ./build.sh scroll.jsonnet
          