name: Update yaml

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source:
        description: 'Source file'
        required: true
      target:
        description: 'Target'
        required: true
      value:
        description: 'Value'
        required: true

jobs:
  update-monitoring:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.source == null }}
    steps:
      - uses: actions/checkout@v2

      - name: Update manifests operation
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/matanki-saito/localservers-private/actions/workflows/update.yaml/dispatches \
          -d "{\"ref\":\"main\", \"inputs\": { \"target\":\"monitoring\"}}"
      
  update-target-yaml:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.source != null }}
    steps:
      - uses: actions/checkout@v2

      - name: Update target yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ github.event.inputs.source }}
          propertyPath: ${{ github.event.inputs.target }}
          value:  ${{ github.event.inputs.value }}
          commitChange: true
          branch: main
          targetBranch: main
          masterBranchName: main
          message: 'updated!'
