name: Update yaml

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        description: 'Target'
        required: true
      value:
        description: 'Value'
        required: true

jobs:
  update-monitoring:
    runs-on: ubuntu-latest
    container:
      image: quay.io/coreos/jsonnet-ci
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          cd monitoring
          rm -rf manifests/*
          jb update
          jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.8
          ls
          ./build.sh scroll.jsonnet

      - name: push yaml
        run: |
          dir
          git config --global user.email "matanki.saito@gmail.com"
          git config --global user.name "matanki.saito"
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git add -A
          git commit -m "Save/Update files [ci skip]"
          git push origin HEAD:main
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        continue-on-error: true
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update target.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'target.yaml'
          propertyPath: ${{ github.event.inputs.target }}
          value:  ${{ github.event.inputs.value }}
          commitChange: true
          message: 'updated!'
